# Generated by Django 5.2.7 on 2026-06-17 13:03

import uuid

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='django_plug_name_73298a_idx'),
                            models.Index(fields=['manager'], name='django_plug_manager_593144_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('name', 'manager'), name='unique_plugin_type_name_manager')],
            },
        ),
        migrations.CreateModel(
            name='PluginItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(editable=False, max_length=100)),
                ('name', models.CharField(db_index=True, editable=False, max_length=100)),
                ('configurable', models.BooleanField(default=False, editable=False)),
                ('priority', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('plugin_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                                  to='django_plugin_system.plugintype')),
            ],
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('config', encrypted_fields.fields.EncryptedJSONField(null=True)),
                ('status',
                 models.CharField(choices=[('active', 'Active'), ('reserve', 'Reserved'), ('disable', 'Disabled')],
                                  db_index=True, default='active', max_length=10)),
                ('priority', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances',
                                           to='django_plugin_system.pluginitem')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'status', 'priority'], name='django_plug_item_id_468df3_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('item', 'name'), name='unique_plugin_instance_item_name')],
            },
        ),
        migrations.AddIndex(
            model_name='pluginitem',
            index=models.Index(fields=['plugin_type'], name='django_plug_plugin__93c8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginitem',
            index=models.Index(fields=['module'], name='django_plug_module_1bcece_idx'),
        ),
        migrations.AddConstraint(
            model_name='pluginitem',
            constraint=models.UniqueConstraint(fields=('name', 'module', 'plugin_type'),
                                               name='unique_plugin_item_name_module_type'),
        ),
    ]
